#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace One.SIG.Sistema.Datos.Paradise
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Paradise")]
	public partial class DBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertPASAJEROS(PASAJEROS instance);
    partial void UpdatePASAJEROS(PASAJEROS instance);
    partial void DeletePASAJEROS(PASAJEROS instance);
    #endregion
		
		public DBDataContext() : 
				base(global::One.SIG.Sistema.Datos.Paradise.Properties.Settings.Default.ParadiseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PASAJEROS> PASAJEROS
		{
			get
			{
				return this.GetTable<PASAJEROS>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PASAJEROS")]
	public partial class PASAJEROS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PaxCod;
		
		private string _PaxRazon;
		
		private string _PaxDirFac;
		
		private System.Nullable<char> _PaxTipo;
		
		private string _PaxNom;
		
		private string _PaxNom1;
		
		private string _PaxApe;
		
		private string _PaxApe1;
		
		private System.Nullable<System.DateTime> _PaxFecNac;
		
		private System.Nullable<short> _PaxSex;
		
		private string _PaxNac;
		
		private System.Nullable<decimal> _PaxRuc;
		
		private string _PaxOcu;
		
		private System.Nullable<char> _PaxCiv;
		
		private string _PaxDir;
		
		private System.Nullable<short> _Paxdescu;
		
		private string _PaxDirLoc;
		
		private string _PaxDirPais;
		
		private string _PaxTel;
		
		private string _PaxFax;
		
		private string _PaxEmail;
		
		private string _PaxCP;
		
		private string _PaxObs;
		
		private string _PaxTipDoc;
		
		private string _PaxNroDoc;
		
		private string _PaxEst;
		
		private System.Nullable<char> _PaxEstPax;
		
		private System.Nullable<System.DateTime> _PaxEveFec;
		
		private System.Nullable<short> _CliBanId;
		
		private string _CliBanSuc;
		
		private System.Nullable<decimal> _CliBanCue;
		
		private string _CliBanTit;
		
		private System.Nullable<short> _CliBanMonId;
		
		private System.Nullable<System.DateTime> _CliFecPag;
		
		private System.Nullable<decimal> _CliTopMN;
		
		private System.Nullable<decimal> _CliTopME;
		
		private System.Nullable<decimal> _CliSalMN;
		
		private System.Nullable<decimal> _CliSalME;
		
		private System.Nullable<decimal> _CliEntCtaPes;
		
		private System.Nullable<decimal> _CliEntCtaDol;
		
		private string _DepCod;
		
		private string _PaxPlaCier;
		
		private string _CliDsc;
		
		private string _PaxProced;
		
		private System.Nullable<System.DateTime> _PaxIngreso;
		
		private System.Nullable<short> _PaxEdades;
		
		private System.Nullable<System.DateTime> _PaxUltEstadia;
		
		private System.Nullable<int> _ContId;
		
		private string _PaxEsquina;
		
		private string _PaxCodMan;
		
		private System.Nullable<int> _PaxPlaCtaCTra;
		
		private System.Nullable<char> _TipoDeDocumentoComprador;
		
		private System.Nullable<char> _ResponsabilidadIvaComprador;
		
		private System.Nullable<char> _PaxControlTopeCredito;
		
		private System.Nullable<char> _PaxCanje;
		
		private string _PaxDepFac;
		
		private string _PaxCiuFac;
		
		private System.Nullable<short> _PaxLisId;
		
		private System.Nullable<char> _PaxLey15921;
		
		private string _PaxNumApartamento;
		
		private System.Nullable<char> _PaxNumBis;
		
		private System.Nullable<char> _PaxTipoCasaDelivery;
		
		private string _PaxNumeroDePuerta;
		
		private string _PaxEsquina2;
		
		private System.Nullable<short> _PaxBarId;
		
		private System.Nullable<short> _ConVenId;
		
		private System.Nullable<int> _Pax0ExportacionId;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPaxCodChanging(int value);
    partial void OnPaxCodChanged();
    partial void OnPaxRazonChanging(string value);
    partial void OnPaxRazonChanged();
    partial void OnPaxDirFacChanging(string value);
    partial void OnPaxDirFacChanged();
    partial void OnPaxTipoChanging(System.Nullable<char> value);
    partial void OnPaxTipoChanged();
    partial void OnPaxNomChanging(string value);
    partial void OnPaxNomChanged();
    partial void OnPaxNom1Changing(string value);
    partial void OnPaxNom1Changed();
    partial void OnPaxApeChanging(string value);
    partial void OnPaxApeChanged();
    partial void OnPaxApe1Changing(string value);
    partial void OnPaxApe1Changed();
    partial void OnPaxFecNacChanging(System.Nullable<System.DateTime> value);
    partial void OnPaxFecNacChanged();
    partial void OnPaxSexChanging(System.Nullable<short> value);
    partial void OnPaxSexChanged();
    partial void OnPaxNacChanging(string value);
    partial void OnPaxNacChanged();
    partial void OnPaxRucChanging(System.Nullable<decimal> value);
    partial void OnPaxRucChanged();
    partial void OnPaxOcuChanging(string value);
    partial void OnPaxOcuChanged();
    partial void OnPaxCivChanging(System.Nullable<char> value);
    partial void OnPaxCivChanged();
    partial void OnPaxDirChanging(string value);
    partial void OnPaxDirChanged();
    partial void OnPaxdescuChanging(System.Nullable<short> value);
    partial void OnPaxdescuChanged();
    partial void OnPaxDirLocChanging(string value);
    partial void OnPaxDirLocChanged();
    partial void OnPaxDirPaisChanging(string value);
    partial void OnPaxDirPaisChanged();
    partial void OnPaxTelChanging(string value);
    partial void OnPaxTelChanged();
    partial void OnPaxFaxChanging(string value);
    partial void OnPaxFaxChanged();
    partial void OnPaxEmailChanging(string value);
    partial void OnPaxEmailChanged();
    partial void OnPaxCPChanging(string value);
    partial void OnPaxCPChanged();
    partial void OnPaxObsChanging(string value);
    partial void OnPaxObsChanged();
    partial void OnPaxTipDocChanging(string value);
    partial void OnPaxTipDocChanged();
    partial void OnPaxNroDocChanging(string value);
    partial void OnPaxNroDocChanged();
    partial void OnPaxEstChanging(string value);
    partial void OnPaxEstChanged();
    partial void OnPaxEstPaxChanging(System.Nullable<char> value);
    partial void OnPaxEstPaxChanged();
    partial void OnPaxEveFecChanging(System.Nullable<System.DateTime> value);
    partial void OnPaxEveFecChanged();
    partial void OnCliBanIdChanging(System.Nullable<short> value);
    partial void OnCliBanIdChanged();
    partial void OnCliBanSucChanging(string value);
    partial void OnCliBanSucChanged();
    partial void OnCliBanCueChanging(System.Nullable<decimal> value);
    partial void OnCliBanCueChanged();
    partial void OnCliBanTitChanging(string value);
    partial void OnCliBanTitChanged();
    partial void OnCliBanMonIdChanging(System.Nullable<short> value);
    partial void OnCliBanMonIdChanged();
    partial void OnCliFecPagChanging(System.Nullable<System.DateTime> value);
    partial void OnCliFecPagChanged();
    partial void OnCliTopMNChanging(System.Nullable<decimal> value);
    partial void OnCliTopMNChanged();
    partial void OnCliTopMEChanging(System.Nullable<decimal> value);
    partial void OnCliTopMEChanged();
    partial void OnCliSalMNChanging(System.Nullable<decimal> value);
    partial void OnCliSalMNChanged();
    partial void OnCliSalMEChanging(System.Nullable<decimal> value);
    partial void OnCliSalMEChanged();
    partial void OnCliEntCtaPesChanging(System.Nullable<decimal> value);
    partial void OnCliEntCtaPesChanged();
    partial void OnCliEntCtaDolChanging(System.Nullable<decimal> value);
    partial void OnCliEntCtaDolChanged();
    partial void OnDepCodChanging(string value);
    partial void OnDepCodChanged();
    partial void OnPaxPlaCierChanging(string value);
    partial void OnPaxPlaCierChanged();
    partial void OnCliDscChanging(string value);
    partial void OnCliDscChanged();
    partial void OnPaxProcedChanging(string value);
    partial void OnPaxProcedChanged();
    partial void OnPaxIngresoChanging(System.Nullable<System.DateTime> value);
    partial void OnPaxIngresoChanged();
    partial void OnPaxEdadesChanging(System.Nullable<short> value);
    partial void OnPaxEdadesChanged();
    partial void OnPaxUltEstadiaChanging(System.Nullable<System.DateTime> value);
    partial void OnPaxUltEstadiaChanged();
    partial void OnContIdChanging(System.Nullable<int> value);
    partial void OnContIdChanged();
    partial void OnPaxEsquinaChanging(string value);
    partial void OnPaxEsquinaChanged();
    partial void OnPaxCodManChanging(string value);
    partial void OnPaxCodManChanged();
    partial void OnPaxPlaCtaCTraChanging(System.Nullable<int> value);
    partial void OnPaxPlaCtaCTraChanged();
    partial void OnTipoDeDocumentoCompradorChanging(System.Nullable<char> value);
    partial void OnTipoDeDocumentoCompradorChanged();
    partial void OnResponsabilidadIvaCompradorChanging(System.Nullable<char> value);
    partial void OnResponsabilidadIvaCompradorChanged();
    partial void OnPaxControlTopeCreditoChanging(System.Nullable<char> value);
    partial void OnPaxControlTopeCreditoChanged();
    partial void OnPaxCanjeChanging(System.Nullable<char> value);
    partial void OnPaxCanjeChanged();
    partial void OnPaxDepFacChanging(string value);
    partial void OnPaxDepFacChanged();
    partial void OnPaxCiuFacChanging(string value);
    partial void OnPaxCiuFacChanged();
    partial void OnPaxLisIdChanging(System.Nullable<short> value);
    partial void OnPaxLisIdChanged();
    partial void OnPaxLey15921Changing(System.Nullable<char> value);
    partial void OnPaxLey15921Changed();
    partial void OnPaxNumApartamentoChanging(string value);
    partial void OnPaxNumApartamentoChanged();
    partial void OnPaxNumBisChanging(System.Nullable<char> value);
    partial void OnPaxNumBisChanged();
    partial void OnPaxTipoCasaDeliveryChanging(System.Nullable<char> value);
    partial void OnPaxTipoCasaDeliveryChanged();
    partial void OnPaxNumeroDePuertaChanging(string value);
    partial void OnPaxNumeroDePuertaChanged();
    partial void OnPaxEsquina2Changing(string value);
    partial void OnPaxEsquina2Changed();
    partial void OnPaxBarIdChanging(System.Nullable<short> value);
    partial void OnPaxBarIdChanged();
    partial void OnConVenIdChanging(System.Nullable<short> value);
    partial void OnConVenIdChanged();
    partial void OnPax0ExportacionIdChanging(System.Nullable<int> value);
    partial void OnPax0ExportacionIdChanged();
    #endregion
		
		public PASAJEROS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxCod", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PaxCod
		{
			get
			{
				return this._PaxCod;
			}
			set
			{
				if ((this._PaxCod != value))
				{
					this.OnPaxCodChanging(value);
					this.SendPropertyChanging();
					this._PaxCod = value;
					this.SendPropertyChanged("PaxCod");
					this.OnPaxCodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxRazon", DbType="Char(40)")]
		public string PaxRazon
		{
			get
			{
				return this._PaxRazon;
			}
			set
			{
				if ((this._PaxRazon != value))
				{
					this.OnPaxRazonChanging(value);
					this.SendPropertyChanging();
					this._PaxRazon = value;
					this.SendPropertyChanged("PaxRazon");
					this.OnPaxRazonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxDirFac", DbType="Char(40)")]
		public string PaxDirFac
		{
			get
			{
				return this._PaxDirFac;
			}
			set
			{
				if ((this._PaxDirFac != value))
				{
					this.OnPaxDirFacChanging(value);
					this.SendPropertyChanging();
					this._PaxDirFac = value;
					this.SendPropertyChanged("PaxDirFac");
					this.OnPaxDirFacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxTipo", DbType="Char(1)")]
		public System.Nullable<char> PaxTipo
		{
			get
			{
				return this._PaxTipo;
			}
			set
			{
				if ((this._PaxTipo != value))
				{
					this.OnPaxTipoChanging(value);
					this.SendPropertyChanging();
					this._PaxTipo = value;
					this.SendPropertyChanged("PaxTipo");
					this.OnPaxTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxNom", DbType="Char(15)")]
		public string PaxNom
		{
			get
			{
				return this._PaxNom;
			}
			set
			{
				if ((this._PaxNom != value))
				{
					this.OnPaxNomChanging(value);
					this.SendPropertyChanging();
					this._PaxNom = value;
					this.SendPropertyChanged("PaxNom");
					this.OnPaxNomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxNom1", DbType="Char(15)")]
		public string PaxNom1
		{
			get
			{
				return this._PaxNom1;
			}
			set
			{
				if ((this._PaxNom1 != value))
				{
					this.OnPaxNom1Changing(value);
					this.SendPropertyChanging();
					this._PaxNom1 = value;
					this.SendPropertyChanged("PaxNom1");
					this.OnPaxNom1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxApe", DbType="Char(15)")]
		public string PaxApe
		{
			get
			{
				return this._PaxApe;
			}
			set
			{
				if ((this._PaxApe != value))
				{
					this.OnPaxApeChanging(value);
					this.SendPropertyChanging();
					this._PaxApe = value;
					this.SendPropertyChanged("PaxApe");
					this.OnPaxApeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxApe1", DbType="Char(15)")]
		public string PaxApe1
		{
			get
			{
				return this._PaxApe1;
			}
			set
			{
				if ((this._PaxApe1 != value))
				{
					this.OnPaxApe1Changing(value);
					this.SendPropertyChanging();
					this._PaxApe1 = value;
					this.SendPropertyChanged("PaxApe1");
					this.OnPaxApe1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxFecNac", DbType="DateTime")]
		public System.Nullable<System.DateTime> PaxFecNac
		{
			get
			{
				return this._PaxFecNac;
			}
			set
			{
				if ((this._PaxFecNac != value))
				{
					this.OnPaxFecNacChanging(value);
					this.SendPropertyChanging();
					this._PaxFecNac = value;
					this.SendPropertyChanged("PaxFecNac");
					this.OnPaxFecNacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxSex", DbType="SmallInt")]
		public System.Nullable<short> PaxSex
		{
			get
			{
				return this._PaxSex;
			}
			set
			{
				if ((this._PaxSex != value))
				{
					this.OnPaxSexChanging(value);
					this.SendPropertyChanging();
					this._PaxSex = value;
					this.SendPropertyChanged("PaxSex");
					this.OnPaxSexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxNac", DbType="Char(3)")]
		public string PaxNac
		{
			get
			{
				return this._PaxNac;
			}
			set
			{
				if ((this._PaxNac != value))
				{
					this.OnPaxNacChanging(value);
					this.SendPropertyChanging();
					this._PaxNac = value;
					this.SendPropertyChanged("PaxNac");
					this.OnPaxNacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxRuc", DbType="Decimal(15,0)")]
		public System.Nullable<decimal> PaxRuc
		{
			get
			{
				return this._PaxRuc;
			}
			set
			{
				if ((this._PaxRuc != value))
				{
					this.OnPaxRucChanging(value);
					this.SendPropertyChanging();
					this._PaxRuc = value;
					this.SendPropertyChanged("PaxRuc");
					this.OnPaxRucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxOcu", DbType="Char(3)")]
		public string PaxOcu
		{
			get
			{
				return this._PaxOcu;
			}
			set
			{
				if ((this._PaxOcu != value))
				{
					this.OnPaxOcuChanging(value);
					this.SendPropertyChanging();
					this._PaxOcu = value;
					this.SendPropertyChanged("PaxOcu");
					this.OnPaxOcuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxCiv", DbType="Char(1)")]
		public System.Nullable<char> PaxCiv
		{
			get
			{
				return this._PaxCiv;
			}
			set
			{
				if ((this._PaxCiv != value))
				{
					this.OnPaxCivChanging(value);
					this.SendPropertyChanging();
					this._PaxCiv = value;
					this.SendPropertyChanged("PaxCiv");
					this.OnPaxCivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxDir", DbType="Char(40)")]
		public string PaxDir
		{
			get
			{
				return this._PaxDir;
			}
			set
			{
				if ((this._PaxDir != value))
				{
					this.OnPaxDirChanging(value);
					this.SendPropertyChanging();
					this._PaxDir = value;
					this.SendPropertyChanged("PaxDir");
					this.OnPaxDirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Paxdescu", DbType="SmallInt")]
		public System.Nullable<short> Paxdescu
		{
			get
			{
				return this._Paxdescu;
			}
			set
			{
				if ((this._Paxdescu != value))
				{
					this.OnPaxdescuChanging(value);
					this.SendPropertyChanging();
					this._Paxdescu = value;
					this.SendPropertyChanged("Paxdescu");
					this.OnPaxdescuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxDirLoc", DbType="Char(20)")]
		public string PaxDirLoc
		{
			get
			{
				return this._PaxDirLoc;
			}
			set
			{
				if ((this._PaxDirLoc != value))
				{
					this.OnPaxDirLocChanging(value);
					this.SendPropertyChanging();
					this._PaxDirLoc = value;
					this.SendPropertyChanged("PaxDirLoc");
					this.OnPaxDirLocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxDirPais", DbType="Char(20)")]
		public string PaxDirPais
		{
			get
			{
				return this._PaxDirPais;
			}
			set
			{
				if ((this._PaxDirPais != value))
				{
					this.OnPaxDirPaisChanging(value);
					this.SendPropertyChanging();
					this._PaxDirPais = value;
					this.SendPropertyChanged("PaxDirPais");
					this.OnPaxDirPaisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxTel", DbType="Char(20)")]
		public string PaxTel
		{
			get
			{
				return this._PaxTel;
			}
			set
			{
				if ((this._PaxTel != value))
				{
					this.OnPaxTelChanging(value);
					this.SendPropertyChanging();
					this._PaxTel = value;
					this.SendPropertyChanged("PaxTel");
					this.OnPaxTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxFax", DbType="Char(20)")]
		public string PaxFax
		{
			get
			{
				return this._PaxFax;
			}
			set
			{
				if ((this._PaxFax != value))
				{
					this.OnPaxFaxChanging(value);
					this.SendPropertyChanging();
					this._PaxFax = value;
					this.SendPropertyChanged("PaxFax");
					this.OnPaxFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxEmail", DbType="Char(40)")]
		public string PaxEmail
		{
			get
			{
				return this._PaxEmail;
			}
			set
			{
				if ((this._PaxEmail != value))
				{
					this.OnPaxEmailChanging(value);
					this.SendPropertyChanging();
					this._PaxEmail = value;
					this.SendPropertyChanged("PaxEmail");
					this.OnPaxEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxCP", DbType="Char(10)")]
		public string PaxCP
		{
			get
			{
				return this._PaxCP;
			}
			set
			{
				if ((this._PaxCP != value))
				{
					this.OnPaxCPChanging(value);
					this.SendPropertyChanging();
					this._PaxCP = value;
					this.SendPropertyChanged("PaxCP");
					this.OnPaxCPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxObs", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string PaxObs
		{
			get
			{
				return this._PaxObs;
			}
			set
			{
				if ((this._PaxObs != value))
				{
					this.OnPaxObsChanging(value);
					this.SendPropertyChanging();
					this._PaxObs = value;
					this.SendPropertyChanged("PaxObs");
					this.OnPaxObsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxTipDoc", DbType="Char(2)")]
		public string PaxTipDoc
		{
			get
			{
				return this._PaxTipDoc;
			}
			set
			{
				if ((this._PaxTipDoc != value))
				{
					this.OnPaxTipDocChanging(value);
					this.SendPropertyChanging();
					this._PaxTipDoc = value;
					this.SendPropertyChanged("PaxTipDoc");
					this.OnPaxTipDocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxNroDoc", DbType="Char(15)")]
		public string PaxNroDoc
		{
			get
			{
				return this._PaxNroDoc;
			}
			set
			{
				if ((this._PaxNroDoc != value))
				{
					this.OnPaxNroDocChanging(value);
					this.SendPropertyChanging();
					this._PaxNroDoc = value;
					this.SendPropertyChanged("PaxNroDoc");
					this.OnPaxNroDocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxEst", DbType="Char(3)")]
		public string PaxEst
		{
			get
			{
				return this._PaxEst;
			}
			set
			{
				if ((this._PaxEst != value))
				{
					this.OnPaxEstChanging(value);
					this.SendPropertyChanging();
					this._PaxEst = value;
					this.SendPropertyChanged("PaxEst");
					this.OnPaxEstChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxEstPax", DbType="Char(1)")]
		public System.Nullable<char> PaxEstPax
		{
			get
			{
				return this._PaxEstPax;
			}
			set
			{
				if ((this._PaxEstPax != value))
				{
					this.OnPaxEstPaxChanging(value);
					this.SendPropertyChanging();
					this._PaxEstPax = value;
					this.SendPropertyChanged("PaxEstPax");
					this.OnPaxEstPaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxEveFec", DbType="DateTime")]
		public System.Nullable<System.DateTime> PaxEveFec
		{
			get
			{
				return this._PaxEveFec;
			}
			set
			{
				if ((this._PaxEveFec != value))
				{
					this.OnPaxEveFecChanging(value);
					this.SendPropertyChanging();
					this._PaxEveFec = value;
					this.SendPropertyChanged("PaxEveFec");
					this.OnPaxEveFecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CliBanId", DbType="SmallInt")]
		public System.Nullable<short> CliBanId
		{
			get
			{
				return this._CliBanId;
			}
			set
			{
				if ((this._CliBanId != value))
				{
					this.OnCliBanIdChanging(value);
					this.SendPropertyChanging();
					this._CliBanId = value;
					this.SendPropertyChanged("CliBanId");
					this.OnCliBanIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CliBanSuc", DbType="Char(40)")]
		public string CliBanSuc
		{
			get
			{
				return this._CliBanSuc;
			}
			set
			{
				if ((this._CliBanSuc != value))
				{
					this.OnCliBanSucChanging(value);
					this.SendPropertyChanging();
					this._CliBanSuc = value;
					this.SendPropertyChanged("CliBanSuc");
					this.OnCliBanSucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CliBanCue", DbType="Decimal(15,0)")]
		public System.Nullable<decimal> CliBanCue
		{
			get
			{
				return this._CliBanCue;
			}
			set
			{
				if ((this._CliBanCue != value))
				{
					this.OnCliBanCueChanging(value);
					this.SendPropertyChanging();
					this._CliBanCue = value;
					this.SendPropertyChanged("CliBanCue");
					this.OnCliBanCueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CliBanTit", DbType="Char(40)")]
		public string CliBanTit
		{
			get
			{
				return this._CliBanTit;
			}
			set
			{
				if ((this._CliBanTit != value))
				{
					this.OnCliBanTitChanging(value);
					this.SendPropertyChanging();
					this._CliBanTit = value;
					this.SendPropertyChanged("CliBanTit");
					this.OnCliBanTitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CliBanMonId", DbType="SmallInt")]
		public System.Nullable<short> CliBanMonId
		{
			get
			{
				return this._CliBanMonId;
			}
			set
			{
				if ((this._CliBanMonId != value))
				{
					this.OnCliBanMonIdChanging(value);
					this.SendPropertyChanging();
					this._CliBanMonId = value;
					this.SendPropertyChanged("CliBanMonId");
					this.OnCliBanMonIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CliFecPag", DbType="DateTime")]
		public System.Nullable<System.DateTime> CliFecPag
		{
			get
			{
				return this._CliFecPag;
			}
			set
			{
				if ((this._CliFecPag != value))
				{
					this.OnCliFecPagChanging(value);
					this.SendPropertyChanging();
					this._CliFecPag = value;
					this.SendPropertyChanged("CliFecPag");
					this.OnCliFecPagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CliTopMN", DbType="Money")]
		public System.Nullable<decimal> CliTopMN
		{
			get
			{
				return this._CliTopMN;
			}
			set
			{
				if ((this._CliTopMN != value))
				{
					this.OnCliTopMNChanging(value);
					this.SendPropertyChanging();
					this._CliTopMN = value;
					this.SendPropertyChanged("CliTopMN");
					this.OnCliTopMNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CliTopME", DbType="Money")]
		public System.Nullable<decimal> CliTopME
		{
			get
			{
				return this._CliTopME;
			}
			set
			{
				if ((this._CliTopME != value))
				{
					this.OnCliTopMEChanging(value);
					this.SendPropertyChanging();
					this._CliTopME = value;
					this.SendPropertyChanged("CliTopME");
					this.OnCliTopMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CliSalMN", DbType="Money")]
		public System.Nullable<decimal> CliSalMN
		{
			get
			{
				return this._CliSalMN;
			}
			set
			{
				if ((this._CliSalMN != value))
				{
					this.OnCliSalMNChanging(value);
					this.SendPropertyChanging();
					this._CliSalMN = value;
					this.SendPropertyChanged("CliSalMN");
					this.OnCliSalMNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CliSalME", DbType="Money")]
		public System.Nullable<decimal> CliSalME
		{
			get
			{
				return this._CliSalME;
			}
			set
			{
				if ((this._CliSalME != value))
				{
					this.OnCliSalMEChanging(value);
					this.SendPropertyChanging();
					this._CliSalME = value;
					this.SendPropertyChanged("CliSalME");
					this.OnCliSalMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CliEntCtaPes", DbType="Money")]
		public System.Nullable<decimal> CliEntCtaPes
		{
			get
			{
				return this._CliEntCtaPes;
			}
			set
			{
				if ((this._CliEntCtaPes != value))
				{
					this.OnCliEntCtaPesChanging(value);
					this.SendPropertyChanging();
					this._CliEntCtaPes = value;
					this.SendPropertyChanged("CliEntCtaPes");
					this.OnCliEntCtaPesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CliEntCtaDol", DbType="Money")]
		public System.Nullable<decimal> CliEntCtaDol
		{
			get
			{
				return this._CliEntCtaDol;
			}
			set
			{
				if ((this._CliEntCtaDol != value))
				{
					this.OnCliEntCtaDolChanging(value);
					this.SendPropertyChanging();
					this._CliEntCtaDol = value;
					this.SendPropertyChanged("CliEntCtaDol");
					this.OnCliEntCtaDolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepCod", DbType="Char(3)")]
		public string DepCod
		{
			get
			{
				return this._DepCod;
			}
			set
			{
				if ((this._DepCod != value))
				{
					this.OnDepCodChanging(value);
					this.SendPropertyChanging();
					this._DepCod = value;
					this.SendPropertyChanged("DepCod");
					this.OnDepCodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxPlaCier", DbType="Char(15)")]
		public string PaxPlaCier
		{
			get
			{
				return this._PaxPlaCier;
			}
			set
			{
				if ((this._PaxPlaCier != value))
				{
					this.OnPaxPlaCierChanging(value);
					this.SendPropertyChanging();
					this._PaxPlaCier = value;
					this.SendPropertyChanged("PaxPlaCier");
					this.OnPaxPlaCierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CliDsc", DbType="Char(40)")]
		public string CliDsc
		{
			get
			{
				return this._CliDsc;
			}
			set
			{
				if ((this._CliDsc != value))
				{
					this.OnCliDscChanging(value);
					this.SendPropertyChanging();
					this._CliDsc = value;
					this.SendPropertyChanged("CliDsc");
					this.OnCliDscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxProced", DbType="Char(15)")]
		public string PaxProced
		{
			get
			{
				return this._PaxProced;
			}
			set
			{
				if ((this._PaxProced != value))
				{
					this.OnPaxProcedChanging(value);
					this.SendPropertyChanging();
					this._PaxProced = value;
					this.SendPropertyChanged("PaxProced");
					this.OnPaxProcedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxIngreso", DbType="DateTime")]
		public System.Nullable<System.DateTime> PaxIngreso
		{
			get
			{
				return this._PaxIngreso;
			}
			set
			{
				if ((this._PaxIngreso != value))
				{
					this.OnPaxIngresoChanging(value);
					this.SendPropertyChanging();
					this._PaxIngreso = value;
					this.SendPropertyChanged("PaxIngreso");
					this.OnPaxIngresoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxEdades", DbType="SmallInt")]
		public System.Nullable<short> PaxEdades
		{
			get
			{
				return this._PaxEdades;
			}
			set
			{
				if ((this._PaxEdades != value))
				{
					this.OnPaxEdadesChanging(value);
					this.SendPropertyChanging();
					this._PaxEdades = value;
					this.SendPropertyChanged("PaxEdades");
					this.OnPaxEdadesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxUltEstadia", DbType="DateTime")]
		public System.Nullable<System.DateTime> PaxUltEstadia
		{
			get
			{
				return this._PaxUltEstadia;
			}
			set
			{
				if ((this._PaxUltEstadia != value))
				{
					this.OnPaxUltEstadiaChanging(value);
					this.SendPropertyChanging();
					this._PaxUltEstadia = value;
					this.SendPropertyChanged("PaxUltEstadia");
					this.OnPaxUltEstadiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContId", DbType="Int")]
		public System.Nullable<int> ContId
		{
			get
			{
				return this._ContId;
			}
			set
			{
				if ((this._ContId != value))
				{
					this.OnContIdChanging(value);
					this.SendPropertyChanging();
					this._ContId = value;
					this.SendPropertyChanged("ContId");
					this.OnContIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxEsquina", DbType="Char(40)")]
		public string PaxEsquina
		{
			get
			{
				return this._PaxEsquina;
			}
			set
			{
				if ((this._PaxEsquina != value))
				{
					this.OnPaxEsquinaChanging(value);
					this.SendPropertyChanging();
					this._PaxEsquina = value;
					this.SendPropertyChanged("PaxEsquina");
					this.OnPaxEsquinaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxCodMan", DbType="Char(10)")]
		public string PaxCodMan
		{
			get
			{
				return this._PaxCodMan;
			}
			set
			{
				if ((this._PaxCodMan != value))
				{
					this.OnPaxCodManChanging(value);
					this.SendPropertyChanging();
					this._PaxCodMan = value;
					this.SendPropertyChanged("PaxCodMan");
					this.OnPaxCodManChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxPlaCtaCTra", DbType="Int")]
		public System.Nullable<int> PaxPlaCtaCTra
		{
			get
			{
				return this._PaxPlaCtaCTra;
			}
			set
			{
				if ((this._PaxPlaCtaCTra != value))
				{
					this.OnPaxPlaCtaCTraChanging(value);
					this.SendPropertyChanging();
					this._PaxPlaCtaCTra = value;
					this.SendPropertyChanged("PaxPlaCtaCTra");
					this.OnPaxPlaCtaCTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoDeDocumentoComprador", DbType="Char(1)")]
		public System.Nullable<char> TipoDeDocumentoComprador
		{
			get
			{
				return this._TipoDeDocumentoComprador;
			}
			set
			{
				if ((this._TipoDeDocumentoComprador != value))
				{
					this.OnTipoDeDocumentoCompradorChanging(value);
					this.SendPropertyChanging();
					this._TipoDeDocumentoComprador = value;
					this.SendPropertyChanged("TipoDeDocumentoComprador");
					this.OnTipoDeDocumentoCompradorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResponsabilidadIvaComprador", DbType="Char(1)")]
		public System.Nullable<char> ResponsabilidadIvaComprador
		{
			get
			{
				return this._ResponsabilidadIvaComprador;
			}
			set
			{
				if ((this._ResponsabilidadIvaComprador != value))
				{
					this.OnResponsabilidadIvaCompradorChanging(value);
					this.SendPropertyChanging();
					this._ResponsabilidadIvaComprador = value;
					this.SendPropertyChanged("ResponsabilidadIvaComprador");
					this.OnResponsabilidadIvaCompradorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxControlTopeCredito", DbType="Char(1)")]
		public System.Nullable<char> PaxControlTopeCredito
		{
			get
			{
				return this._PaxControlTopeCredito;
			}
			set
			{
				if ((this._PaxControlTopeCredito != value))
				{
					this.OnPaxControlTopeCreditoChanging(value);
					this.SendPropertyChanging();
					this._PaxControlTopeCredito = value;
					this.SendPropertyChanged("PaxControlTopeCredito");
					this.OnPaxControlTopeCreditoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxCanje", DbType="Char(1)")]
		public System.Nullable<char> PaxCanje
		{
			get
			{
				return this._PaxCanje;
			}
			set
			{
				if ((this._PaxCanje != value))
				{
					this.OnPaxCanjeChanging(value);
					this.SendPropertyChanging();
					this._PaxCanje = value;
					this.SendPropertyChanged("PaxCanje");
					this.OnPaxCanjeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxDepFac", DbType="Char(30)")]
		public string PaxDepFac
		{
			get
			{
				return this._PaxDepFac;
			}
			set
			{
				if ((this._PaxDepFac != value))
				{
					this.OnPaxDepFacChanging(value);
					this.SendPropertyChanging();
					this._PaxDepFac = value;
					this.SendPropertyChanged("PaxDepFac");
					this.OnPaxDepFacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxCiuFac", DbType="Char(30)")]
		public string PaxCiuFac
		{
			get
			{
				return this._PaxCiuFac;
			}
			set
			{
				if ((this._PaxCiuFac != value))
				{
					this.OnPaxCiuFacChanging(value);
					this.SendPropertyChanging();
					this._PaxCiuFac = value;
					this.SendPropertyChanged("PaxCiuFac");
					this.OnPaxCiuFacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxLisId", DbType="SmallInt")]
		public System.Nullable<short> PaxLisId
		{
			get
			{
				return this._PaxLisId;
			}
			set
			{
				if ((this._PaxLisId != value))
				{
					this.OnPaxLisIdChanging(value);
					this.SendPropertyChanging();
					this._PaxLisId = value;
					this.SendPropertyChanged("PaxLisId");
					this.OnPaxLisIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxLey15921", DbType="Char(1)")]
		public System.Nullable<char> PaxLey15921
		{
			get
			{
				return this._PaxLey15921;
			}
			set
			{
				if ((this._PaxLey15921 != value))
				{
					this.OnPaxLey15921Changing(value);
					this.SendPropertyChanging();
					this._PaxLey15921 = value;
					this.SendPropertyChanged("PaxLey15921");
					this.OnPaxLey15921Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxNumApartamento", DbType="Char(10)")]
		public string PaxNumApartamento
		{
			get
			{
				return this._PaxNumApartamento;
			}
			set
			{
				if ((this._PaxNumApartamento != value))
				{
					this.OnPaxNumApartamentoChanging(value);
					this.SendPropertyChanging();
					this._PaxNumApartamento = value;
					this.SendPropertyChanged("PaxNumApartamento");
					this.OnPaxNumApartamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxNumBis", DbType="Char(1)")]
		public System.Nullable<char> PaxNumBis
		{
			get
			{
				return this._PaxNumBis;
			}
			set
			{
				if ((this._PaxNumBis != value))
				{
					this.OnPaxNumBisChanging(value);
					this.SendPropertyChanging();
					this._PaxNumBis = value;
					this.SendPropertyChanged("PaxNumBis");
					this.OnPaxNumBisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxTipoCasaDelivery", DbType="Char(1)")]
		public System.Nullable<char> PaxTipoCasaDelivery
		{
			get
			{
				return this._PaxTipoCasaDelivery;
			}
			set
			{
				if ((this._PaxTipoCasaDelivery != value))
				{
					this.OnPaxTipoCasaDeliveryChanging(value);
					this.SendPropertyChanging();
					this._PaxTipoCasaDelivery = value;
					this.SendPropertyChanged("PaxTipoCasaDelivery");
					this.OnPaxTipoCasaDeliveryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxNumeroDePuerta", DbType="Char(10)")]
		public string PaxNumeroDePuerta
		{
			get
			{
				return this._PaxNumeroDePuerta;
			}
			set
			{
				if ((this._PaxNumeroDePuerta != value))
				{
					this.OnPaxNumeroDePuertaChanging(value);
					this.SendPropertyChanging();
					this._PaxNumeroDePuerta = value;
					this.SendPropertyChanged("PaxNumeroDePuerta");
					this.OnPaxNumeroDePuertaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxEsquina2", DbType="Char(40)")]
		public string PaxEsquina2
		{
			get
			{
				return this._PaxEsquina2;
			}
			set
			{
				if ((this._PaxEsquina2 != value))
				{
					this.OnPaxEsquina2Changing(value);
					this.SendPropertyChanging();
					this._PaxEsquina2 = value;
					this.SendPropertyChanged("PaxEsquina2");
					this.OnPaxEsquina2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaxBarId", DbType="SmallInt")]
		public System.Nullable<short> PaxBarId
		{
			get
			{
				return this._PaxBarId;
			}
			set
			{
				if ((this._PaxBarId != value))
				{
					this.OnPaxBarIdChanging(value);
					this.SendPropertyChanging();
					this._PaxBarId = value;
					this.SendPropertyChanged("PaxBarId");
					this.OnPaxBarIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConVenId", DbType="SmallInt")]
		public System.Nullable<short> ConVenId
		{
			get
			{
				return this._ConVenId;
			}
			set
			{
				if ((this._ConVenId != value))
				{
					this.OnConVenIdChanging(value);
					this.SendPropertyChanging();
					this._ConVenId = value;
					this.SendPropertyChanged("ConVenId");
					this.OnConVenIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pax0ExportacionId", DbType="Int")]
		public System.Nullable<int> Pax0ExportacionId
		{
			get
			{
				return this._Pax0ExportacionId;
			}
			set
			{
				if ((this._Pax0ExportacionId != value))
				{
					this.OnPax0ExportacionIdChanging(value);
					this.SendPropertyChanging();
					this._Pax0ExportacionId = value;
					this.SendPropertyChanged("Pax0ExportacionId");
					this.OnPax0ExportacionIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
